config/routes.rb
Rails.application.routes.draw do

	root 'public/items#top'
  	get 'home/about', to:'homes#about'

  	devise_for :admins
  	devise_for :customers

  	namespace :admin do
		resources :items, only: [:index, :new, :create, :show, :edit, :update]
		resources :customers, only: [:index, :show, :edit, :update]
		resources :genres, only: [:index, :create, :edit, :update]
		resources :orders, only: [:index, :show, :update]
		resources :order_details, only: [:update]
		# admin のtopページ
		# 注文件数が書かれているページ
		get 'order/top', to:'orders#top'
	end

	namespace :public do
		get 'item/top', to:'items#top'
		get 'order/thanks', to:'orders#thanks'
		get 'customer/confirm', to:'customers#confirm'
		put "/customers/:id/hide" => "customers#hide", as: 'customers_hide'
		delete "cart_item/:id/destroy_all", to: "cart_items#destroy_all"
		resources :customers
		resources :items, only:[:index, :show]
		resources :addresses,only:[:index, :edit, :create, :update, :destroy]
		resources :cart_items, only:[:index, :update, :destroy, :create, :delete] do
			collection do
				delete 'destroy_all'
			end
		end
		resources :orders, only:[:new, :create, :index, :show] do
			collection do
				post :new, path: :new, as: :new, action: :back
				post :confirm
				get :complete
			end
		end
	end
end

app/models/addresse.rb
class Addresse < ApplicationRecord
	belongs_to :customer
	# 空白NG
	validates :address, presence: true
	validates :name, presence: true
	# 文字NG
	validates :postal_code, numericality: true, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :customer
	belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

# 空白NG
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :address, presence: true
# 文字NG
  validates :postal_code, numericality: true, presence: true
  validates :telephone_number, numericality: true, presence: true
# 6文字以下NG
  validates :encrypted_password, length: { minimum: 6 } 
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
	# itemsに多数のデータを送信可能にする
	has_many :items, dependent: :destroy
	# enum is_active: { f: false, t: true }
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
	# genreに一つのデータを送信可能
	belongs_to :genre
	# cart_itemsに多数のデータを送信可能
	has_many :cart_items, dependent: :destroy
	# order_ditailsに多数のデータを送信可能
	has_many :order_details, dependent: :destroy

	# 画像をアップロードするためのattachementメソッドです
	# imageカラムでアップロード可能にしている
	attachment :image
	# validates :name, presence: true
	# validates :introduction, presence: true
	# validates :price, presence: true
	enum is_active: { 販売停止中:0, 販売中:1 }

	 def self.search(search)
      if search
        Item.where(['name LIKE ?', "%#{search}%"])
      else
        Item.all
      end
    end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	# has_many :order_details, dependent: :destroy
	has_many :cart_items, dependent: :destroy
	
	# 注文を新規保存・更新するため
	has_many :order_details, dependent: :destroy
	accepts_nested_attributes_for :order_details

	enum payment_method: { クレジットカード:0, 銀行:1 }
	enum status: {
		入金待ち:0,
		入金確認:1,
		制作中:2,
		発送準備中:3,
		発送済み:4
	}

	# 空白NG
	validates :address, presence: true
	validates :name, presence: true
	validates :customer_id, presence: true
	validates :name, presence: true
	# 文字NG
	validates :postal_code, numericality: true, presence: true



end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	# 注文を保存するため
	belongs_to :order
	# 注文itemを保存するため
	belongs_to :item
	enum make_status: {
		制作不可:0,
		制作待ち:1,
		制作中:2,
		制作完了:3,
	}
	# 空白NG
	validates :item_id, presence: true
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
	before_action :authenticate
	def index
		# indexでは一覧を表示するため
		# インスタンス変数kitemsにItemモデルの中にあるすべてののデータをを代入
		@items = Item.all
	end

	def new
		# form_forヘルパーで入力されたデータを格納する空のItemモデルを作成する
		# それをインスタンス変数に代入する
		@item = Item.new
	end

	def create
		# newアクションで入力されたデータをこのItem.newにいれてストロングパロメータに送信される
		@item = Item.new(item_params)
		# saveメソッドで@Itemに入っているデータをデータベースに保存する
		# 保存できない場合はfalseが返る
		if @item.save
		 # binding.pry
		redirect_to admin_item_path(@item.id)
		else
		 render :new
		end
	end

	def show
		@item = Item.find(params[:id])
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])
		@item.update(item_params)
		redirect_to admin_items_path
	end

	private
	def item_params
		params.require(:item).permit(:genre_id, :name, :introduction, :price, :image, :is_active)
	end
	def authenticate
  		redirect_to admin_session_path unless admin_signed_in?
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# deviseの機能使用される前にconfigure_permitted_parametersが実行されます
before_action :configure_permitted_parameters, if: :devise_controller?

# 新規登録後のpath
def after_sign_up_path_for(resource)
    public_item_top_path
end

# ログイン後のpath
def after_sign_in_path_for(resource)
  case resource
  when Admin
    admin_order_top_path
  when Customer
    public_item_top_path
  end
end

# ログアウト後のリダイレクト先
def after_sign_out_path_for(resource)
  if resource == :admin
    new_admin_session_path
  else
    public_item_top_path
  end
end

protected
  # devise_parameter_sanitizer.permitでlast_nameを操作する許可するアクションメソッドが指定されています
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:postal_code])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:telephone_number])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def about
	end
end

app/helpers/admin/addresses_helper.rb
module Admin::AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/views/admin/items/edit.html.erb
<%= render 'layouts/amin_header' %>
<h1>商品編集</h1>
<%= attachment_image_tag @item, :image, :fill, 60, 60, fallback: "", size:'100x100'%>
<%= form_for(@item, url: admin_item_path) do |f| %>

	<%= f.attachment_field :image %>
	<h2>商品名</h2>
	<%= f.text_field :name%>
	<h2>商品説明</h2>
	<%= f.text_area :introduction %>
	<h2>ジャンル</h2>
	<%= f.collection_select :genre_id, Genre.all, :id, :name %>
	<h2>税抜価格</h2>
	<%= f.text_field :price%>
	<h2>販売ステータス</h2>
	 <%= f.select :is_active, [['販売停止中', '販売停止中'], ['販売中', '販売中']]%>
	 <div class="admin_items_edit">
		<%= f.submit "編集完了",  class: "btn btn-info"%>
	 </div>
<% end %>

app/views/admin/items/index.html.erb
<%= render 'layouts/amin_header' %>
<%= link_to "商品新規登録", new_admin_item_path, class: "btn btn-warning"%>
<h1>商品一覧</h1>

<table class="table">
	<tr>
		<th>商品id</th>
		<th>商品名</th>
		<th>税抜き価格</th>
		<th>ジャンル</th>
		<th>ステータス</th>
	</tr>
	<tr>
		<% @items.each do |i|%>
			<td><%= i.id %></td>
			<td><%= link_to i.name, admin_item_path(i.id) %></td>
			<td><%= i.price %></td>
			<td><%= i.genre.name %></td>
			<td><%= i.is_active %></td>
	</tr>
		<% end %>
</table>

app/views/admin/items/new.html.erb
<%= render 'layouts/amin_header' %>
<h1>商品新規登録</h1>

<!-- form_forで@item(空のモデル)にデータを入れていくこの記述をブロック変数fに代入している -->
<%= form_for(@item, url: admin_items_path) do |f| %>
<!-- attachment_fieldで画像をアップロード出来る(モデルにattachmentを記述してあることが条件) -->
	<%= f.attachment_field :image %>
	<h2>商品名</h2>
	<%= f.text_field :name%>

	<h2>商品説明</h2>
	<%= f.text_area :introduction %>
	<h2>ジャンル</h2>
	<!-- collection_selectは紐づけしているFK(genre_id)を指定することでGenreモデルの中に入ることが出来る,
	そして Genreモデルのデータをすべて取り出し,
	vlue属性にgenresテーブルのidを入れ
	text項目にgenresテーブルのジャンルのnameを表示することができる-->
	<!-- Genre.allの後はすべてgenreモデルのデータのことを示している -->
	<%= f.collection_select :genre_id, Genre.all, :id, :name %>
	<h2>税抜価格</h2>
	<%= f.text_field :price%>

	<h2>販売ステータス</h2>
	<!-- selectで販売停止中を選ぶとfalseがis_activeに入れられる -->
	<!-- selectで販売中を選ぶとtrueがis_activeに入れられる -->
	 <%= f.select :is_active, [['販売停止中', '販売停止中'], ['販売中', '販売中']]%>

	 <!-- @item(空のモデルに)にform_forで入力されたデータが入れられて
	 admin_items_pathのcreateアクションに送信される -->
	<div class="admin_items_edit">
		<%= f.submit "新規商品登録", class: "btn btn-info"%>
	</div>



<% end %>

app/views/admin/items/show.html.erb
<%= render 'layouts/amin_header' %>
<h1>商品詳細</h1>
<%= attachment_image_tag @item, :image, :fill, 60, 60, fallback: "", size:'100x100'%>
<table class="table">
	<tr>
		<th>商品名</th>
		<td><%= @item.name%></td>
	</tr>

	<tr>
		<th>商品紹介</th>
		<td><%= @item.introduction%></td>
	</tr>

	<tr>
		<th>ジャンル</th>
		<td><%= @item.genre.name%></td>
	</tr>

	<tr>
		<th>税込価格</th>
		<td><%= @item.price%>円</td>
	</tr>

	<tr>
		<th>販売ステータス</th>
		<td><%= @item.is_active %></td>
	</tr>
</table>
<%= link_to '商品編集', edit_admin_item_path(@item.id), class: "btn btn-info" %>