config/routes.rb
Rails.application.routes.draw do

	root 'public/items#top'
  	get 'home/about', to:'homes#about'

  	devise_for :admins
  	devise_for :customers

  	namespace :admin do
		resources :items, only: [:index, :new, :create, :show, :edit, :update]
		resources :customers, only: [:index, :show, :edit, :update]
		resources :genres, only: [:index, :create, :edit, :update]
		resources :orders, only: [:index, :show, :update]
		resources :order_details, only: [:update]
		# admin のtopページ
		# 注文件数が書かれているページ
		get 'order/top', to:'orders#top'
	end

	namespace :public do
		get 'item/top', to:'items#top'
		get 'order/thanks', to:'orders#thanks'
		get 'customer/confirm', to:'customers#confirm'
		put "/customers/:id/hide" => "customers#hide", as: 'customers_hide'
		delete "cart_item/:id/destroy_all", to: "cart_items#destroy_all"
		resources :customers
		resources :items, only:[:index, :show]
		resources :addresses,only:[:index, :edit, :create, :update, :destroy]
		resources :cart_items, only:[:index, :update, :destroy, :create, :delete] do
			collection do
				delete 'destroy_all'
			end
		end
		resources :orders, only:[:new, :create, :index, :show] do
			collection do
				post :new, path: :new, as: :new, action: :back
				post :confirm
				get :complete
			end
		end
	end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

# 空白NG
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :address, presence: true
# 文字NG
  validates :postal_code, numericality: true, presence: true
  validates :telephone_number, numericality: true, presence: true
# 6文字以下NG
  validates :encrypted_password, length: { minimum: 6 } 
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
	before_action :authenticate
	def index
		# Customerモデルの中のデータをすべて代入する
		@customers = Customer.all
	end

	def show
		# indexで会員idを持たせてshowに移動している
		# その会員idのデータを見つける(findメソッドで)
		# params[:id]でデータベースから持たされたidのレコードを取得する
		@customer = Customer.find(params[:id])
	end

	def edit
		@customer = Customer.find(params[:id])
	end

	def update
		@customer = Customer.find(params[:id])
		@customer.update(customer_params)
		redirect_to admin_customer_path
	end
	private
	def customer_params
		params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
	end
	def authenticate
  		redirect_to admin_session_path unless admin_signed_in?
	end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]


# # 新規登録後のpath
# def after_sign_up_path_for(resource)
#     public_item_top_path
# end
# # ログイン後のpath
# def after_sign_in_path_for(resource)
#    public_item_top_path
# end

# # ログアウト後のリダイレクト先
# def after_sign_out_path_for(resource)
#   public_item_top_path
# end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<%= render 'layouts/amin_header' %>
<h1><%= @customer.first_name%><%= @customer.last_name%>さんの会員情報編集</h1>
<%= form_for(@customer, url: admin_customer_path) do |f| %>

	 <div class="field">
    <%= f.label :名前 %>
    <%= f.label :'(姓)' %><br>
    <%= f.text_field :first_name, autofocus: true, autocomplete: "姓" %><br>
    <%= f.label :'(名)' %><br>
    <%= f.text_field :last_name, autofocus: true, autocomplete: "名" %>
  </div>

  <div class="field">
    <%= f.label :フリガナ %>
    <%= f.label :'(セイ)' %><br>
    <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "姓" %><br>
    <%= f.label :'(メイ)' %><br>
    <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "名" %>
  </div>

  <div class="field">
    <%= f.label :'郵便番号(ハイフンなし)' %><br>
    <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code" %>
  </div>

   <div class="field">
    <%= f.label :'住所' %><br>
    <%= f.text_field :address, autofocus: true, autocomplete: "address" %>
  </div>

  <div class="field">
    <%= f.label :'電話番号（ハイフンなし）' %><br>
    <%= f.telephone_field :telephone_number, autofocus: true, autocomplete: "telephone_number" %>
  </div>

  <div class="field">
    <%= f.label :メールアドレス %><br>
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="is_active customer_edit_radio">
    <h3>有効</h3>
    <%= f.radio_button :is_deleted, [false] %>
    <h3>退会済み</h3>
    <%= f.radio_button :is_deleted, [true] %>
  </div>

  <div class="actions">
    <%= f.submit "変更を保存する",  class: "btn btn-info" %>
  </div>


<% end %>

app/views/admin/customers/index.html.erb
<%= render 'layouts/amin_header' %>
<h1>会員一覧</h1>

<table class="table">
	<tr>
		<th>会員ID</th>
		<th>氏名</th>
		<th>メールアドレス</th>
		<th>ステータス</th>
	</tr>
		<% @customers.each do |c| %>
	<tr>
			<td><%= c.id%></td>
			<!-- 名前すべてをlink_toにするためにブロックを使用する -->
			<!-- linkに会員のidを持たせてadmin/showに移動 -->
			<td><%= link_to admin_customer_path(c) do %>
				<%= c.first_name%><%= c.last_name%></td>
			<% end %>
			<td><%= c.email%></td>
			<td><% if c.is_deleted == true %>
				退会済み
				<% else %>
				有効
				<% end %>
			</td>
		<% end %>
	</tr>

</table>

app/views/admin/customers/show.html.erb
<%= render 'layouts/amin_header' %>
<h1><%= @customer.first_name%><%= @customer.last_name%>さんの会員詳細</h1>
<table class="table">
	<tr>
		<th>顧客ID</th>
		<td><%= @customer.id %>
			<% if @customer.is_deleted == true %>
				退会済み
			<% else %>
				有効会員
			<% end %>
		</td>
	</tr>
	<tr>
		<th>氏名</th>
		<td><%= @customer.first_name%><%= @customer.last_name%></td>
	</tr>
	<tr>
		<th>郵便番号</th>
		<td><%= @customer.postal_code %></td>
	</tr>
	<tr>
		<th>住所</th>
		<td><%= @customer.address %></td>
	</tr>
	<tr>
		<th>電話番号</th>
		<td><%= @customer.telephone_number %></td>
	</tr>
	<tr>
		<th>メールアドレス</th>
		<td><%= @customer.email %></td>
	</tr>
</table>
<%= link_to '編集する',edit_admin_customer_path(@customer.id) , class: "btn btn-success"%>
<%= link_to '注文履歴一覧を見る',admin_orders_path(@customer.id), class: "btn btn-info" %>