config/routes.rb
Rails.application.routes.draw do

	root 'public/items#top'
  	get 'home/about', to:'homes#about'

  	devise_for :admins
  	devise_for :customers

  	namespace :admin do
		resources :items, only: [:index, :new, :create, :show, :edit, :update]
		resources :customers, only: [:index, :show, :edit, :update]
		resources :genres, only: [:index, :create, :edit, :update]
		resources :orders, only: [:index, :show, :update]
		resources :order_details, only: [:update]
		# admin のtopページ
		# 注文件数が書かれているページ
		get 'order/top', to:'orders#top'
	end

	namespace :public do
		get 'item/top', to:'items#top'
		get 'order/thanks', to:'orders#thanks'
		get 'customer/confirm', to:'customers#confirm'
		put "/customers/:id/hide" => "customers#hide", as: 'customers_hide'
		delete "cart_item/:id/destroy_all", to: "cart_items#destroy_all"
		resources :customers
		resources :items, only:[:index, :show]
		resources :addresses,only:[:index, :edit, :create, :update, :destroy]
		resources :cart_items, only:[:index, :update, :destroy, :create, :delete] do
			collection do
				delete 'destroy_all'
			end
		end
		resources :orders, only:[:new, :create, :index, :show] do
			collection do
				post :new, path: :new, as: :new, action: :back
				post :confirm
				get :complete
			end
		end
	end
end

app/models/addresse.rb
class Addresse < ApplicationRecord
	belongs_to :customer
	# 空白NG
	validates :address, presence: true
	validates :name, presence: true
	# 文字NG
	validates :postal_code, numericality: true, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :customer
	belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

# 空白NG
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :address, presence: true
# 文字NG
  validates :postal_code, numericality: true, presence: true
  validates :telephone_number, numericality: true, presence: true
# 6文字以下NG
  validates :encrypted_password, length: { minimum: 6 } 
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
	# itemsに多数のデータを送信可能にする
	has_many :items, dependent: :destroy
	# enum is_active: { f: false, t: true }
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
	# genreに一つのデータを送信可能
	belongs_to :genre
	# cart_itemsに多数のデータを送信可能
	has_many :cart_items, dependent: :destroy
	# order_ditailsに多数のデータを送信可能
	has_many :order_details, dependent: :destroy

	# 画像をアップロードするためのattachementメソッドです
	# imageカラムでアップロード可能にしている
	attachment :image
	# validates :name, presence: true
	# validates :introduction, presence: true
	# validates :price, presence: true
	enum is_active: { 販売停止中:0, 販売中:1 }

	 def self.search(search)
      if search
        Item.where(['name LIKE ?', "%#{search}%"])
      else
        Item.all
      end
    end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	# has_many :order_details, dependent: :destroy
	has_many :cart_items, dependent: :destroy
	
	# 注文を新規保存・更新するため
	has_many :order_details, dependent: :destroy
	accepts_nested_attributes_for :order_details

	enum payment_method: { クレジットカード:0, 銀行:1 }
	enum status: {
		入金待ち:0,
		入金確認:1,
		制作中:2,
		発送準備中:3,
		発送済み:4
	}

	# 空白NG
	validates :address, presence: true
	validates :name, presence: true
	validates :customer_id, presence: true
	validates :name, presence: true
	# 文字NG
	validates :postal_code, numericality: true, presence: true



end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	# 注文を保存するため
	belongs_to :order
	# 注文itemを保存するため
	belongs_to :item
	enum make_status: {
		制作不可:0,
		制作待ち:1,
		制作中:2,
		制作完了:3,
	}
	# 空白NG
	validates :item_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# deviseの機能使用される前にconfigure_permitted_parametersが実行されます
before_action :configure_permitted_parameters, if: :devise_controller?

# 新規登録後のpath
def after_sign_up_path_for(resource)
    public_item_top_path
end

# ログイン後のpath
def after_sign_in_path_for(resource)
  case resource
  when Admin
    admin_order_top_path
  when Customer
    public_item_top_path
  end
end

# ログアウト後のリダイレクト先
def after_sign_out_path_for(resource)
  if resource == :admin
    new_admin_session_path
  else
    public_item_top_path
  end
end

protected
  # devise_parameter_sanitizer.permitでlast_nameを操作する許可するアクションメソッドが指定されています
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:postal_code])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:telephone_number])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def about
	end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_amin_header.html.erb
<header>
      <div>
        <h1>LOGO</h1>
      </div>
      <% if admin_signed_in? %>
          <div class="link"><%= link_to "商品新規登録", new_admin_item_path%></div>
          <div class="link"><%= link_to '商品一覧', admin_items_path%></div>
          <div class="link"><%= link_to '会員一覧', admin_customers_path%></div>
          <div class="link"><%= link_to '注文履歴一覧', admin_orders_path%></div>
          <div class="link"><%= link_to 'ジャンル一覧', admin_genres_path%></div>
          <div class="link"><%= link_to 'ログアウト',  destroy_admin_session_path, method: :delete %></div>
        <% else %>
          <div class="link"><%= link_to 'About', home_about_path %></div>
          <div class="link"><%= link_to '商品一覧', admin_items_path%></div>
          <div class="link"><%= link_to '新規登録', new_customer_registration_path %></div>
          <div class="link"><%= link_to 'ログイン', new_admin_session_path%></div>
      <% end %>
</header>

app/views/layouts/_customer_header.html.erb
<div class="row">
  <header>
    <div><h1>LOGO</h1></div>
    <% if customer_signed_in? %>
      <strong><%= current_customer.first_name %><%= current_customer.last_name %></strong>さん
      <div class="link"><%= link_to 'マイページ', public_customer_path(current_customer.id) %></div>
      <div class="link"><%= link_to 'トップページ', root_path %></div>
      <div class="link"><%= link_to '商品一覧', public_items_path%></div>
      <div class="link"><%= link_to 'カート', public_cart_items_path%></div>
      <div class="link"><%= link_to 'ログアウト',  destroy_customer_session_path, method: :delete %></div>
    <% else %>
      <div class="link"><%= link_to 'トップページ', root_path %></div>
      <div class="link"><%= link_to 'About', home_about_path %></div>
      <div class="link"><%= link_to '商品一覧', public_items_path%></div>
      <div class="link"><%= link_to '新規登録', new_customer_registration_path %></div>
      <div class="link"><%= link_to 'ログイン', new_customer_session_path%></div>
    <% end %>
  </header>
</div>

app/views/layouts/_error_messages.html.erb
	<!-- エラーがある場合はすべてのメッセージを検証し表示しなさい -->
<% if model.errors.any? %>
		<h2><%= pluralize(model.errors.count, "error") %>prohibited this product from being saved:</h2>
		<% model.errors.full_messages.each do |message| %>
	<ul>
		<li><%= message %></li>
	</ul>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head lang="jp">
    <meta charset="utf-8">
    <title>DwcRailsAppTemplate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>